spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

com:
  vanchondo:
    secret:
      secret-key: ENC(irSPgA6Iu+WckRjiOsKTyXMqDmqxHqIs2PccXumab8Q=)    